///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AnadroidIds
{
        public const string achievement_getting_started = "CgkI9_bnieIZEAIQAA"; // <GPGSID>

}

